# Generated by Django 5.0.6 on 2025-02-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='formacion',
        ),
    ]
